### ISSUE TITLE
How can i get uri of selected file in onRequestHandlePathOz method. [ENHANCEMENT]

### ISSUE THREAD

**Issue by Pradeepkumar2091** [onimur/handle-path-oz#4]
Hello 
Thank you for this wonder full library. it helps a lot.

I wanted to know that how can i get the uri of selected file in `onRequestHandlePathOz ` method. Currently i can see that only type and path is return in this method.

**Comment by onimur** [comment]
Hello thank you for using our library.

The method does not return Uri, just the string with the path.

But to get uri by real path it's simple, in `onRequestHandlePathOz `method, just use:

**Java**
`Uri uri = Uri.parse(pathOz.getPath);`

**Kotlin**
`val uri = pathOz.path.toUri() `

If you have any further questions regarding this I would be happy to help.
