### ISSUE TITLE
[ENHANCEMENT] Ability to handle directories

### ISSUE THREAD

**Issue by mendhak** [onimur/handle-path-oz#5]
**Is your feature request related to a problem? Please describe. 🚀**

Hi, I tried this library and I was not able to convert directory URIs to paths.  Would it be possible that this library can also handle directories?  I can understand if the library wasn't made for that though, so instead is there a way I can derive the path myself? 

I've set up following the wiki instructions.  I launched the directory chooser

```
            Intent directoryChooser = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
            startActivityForResult(directoryChooser, 55);
```

And this was the result that came back

```
021-09-14 18:57:43.140 6066-6066/com.mendhak.gpslogger E/HandlePathOz: StandaloneCoroutine - java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/primary%3AGPSLogger - Unsupported Uri content://com.android.externalstorage.documents/tree/primary%3AGPSLogger
2021-09-14 18:57:43.140 6066-6066/com.mendhak.gpslogger D/LoggingSettingsFragment: onRequestHandlePathOz:292 - The real path is: 
     The type is: 
2021-09-14 18:57:43.140 6066-6066/com.mendhak.gpslogger E/LoggingSettingsFragment: onRequestHandlePathOz:296 - Unsupported Uri content://com.android.externalstorage.documents/tree/primary%3AGPSLogger
2021-09-14 18:57:43.140 6066-6066/com.mendhak.gpslogger D/HandlePathOz: StandaloneCoroutine - MainScope isActive: true
    This Scope isActive: true
    Job isNew: false
    Job isCompleting: true
    Job isCancelling: false
    Job wasCancelled: false
    Job wasCompleted: false
```

**Describe the solution you'd like:**

Would be good if I could get the real path of a directory.  But I can see the problem with handling cloud content providers, there's nothing you can 'copy' locally, so this library probably isn't meant for directories?

**Comment by onimur** [comment]
Sorry for the delay, at the moment I'm busy with other projects, the library was not designed to work with directories, just files. Unfortunately, I don't have the time available at the moment to add this function to the project.
